version: '2'
services:
    project3-app:
        image: project3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://project3-mysql:3306/project3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    project3-mysql:
        extends:
            file: mysql.yml
            service: project3-mysql
